blog_django-dev/blog/urls.py
from django.contrib import admin
# from users.views import index
from django.contrib import admin
from extra_apps import xadmin
from django.urls import path,include
from . views import index

app_name="blog"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name="index"),
    # path('index',my_blog),
    path('xadmin/', xadmin.site.urls),
    path('mydata/', include('mydata.urls')),
    path('users/', include('users.urls'))

]

blog_django-dev/users/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    UsersLogin, UsersLogout, UserRegisterFormView,
    ServerNowListView, ServerDetail, post_data, personal, add, toadd


)
app_name = "users"
urlpatterns = [
    path('login/', UsersLogin.as_view(), name="usersLogin"),
    path('logout/', UsersLogout.as_view(), name="usersLogout"),
    path('register/', UserRegisterFormView.as_view(), name="Register"),
    path("show/", ServerNowListView.as_view(), name="serverNowList"),
    path("post/<int:pk>/", ServerDetail, name="serverdetail"),
    path("post_data/", post_data, name="post_data"),
    path(r'^Add/$', add, name="add_data"),
    path(r'^toadd/$', toadd, name="toadd"),
    path("personal/", personal.as_view(), name="personal"),

]

blog_django-dev/templates/index.html
<html lang="zh-CN">
{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>


    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrp/css/bootstrap.min.css' %}">
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="{% static 'bootstrp/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/vue.min.js' %}"></script>
    <script src="{% static 'js/axios.min.js' %}"></script>
    <!--Axios Ajax-->

    <title>{% block titile %}博客首页{% endblock %}</title>
    <style>
        .nav-head {
            height: 50px;
        }

        .naver {
            height: 30px;
            width: 30px;
        }

        .content {
            margin: 10px 32px 0 20px;
        }
    </style>
    {% block style %}

    {% endblock %}
</head>

<body>
    <div class="container-fluid">
        <header class="row ">
            <nav class="navbar navbar-default nav-head">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#">博客首页</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url 'users:post_data' %}">文章<span class="glyphicon glyphicon-link"></span></a></li>
                                
                            {% if not request.user.is_authenticated %}
                            <li class="active"><a href="{% url 'users:usersLogin' %}">登陆</a></li>
                            <li class="active"><a href="{% url 'users:Register' %}">注册</a></li>
                            {% endif %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                    aria-haspopup="true" aria-expanded="false">{{request.user}}
                                   <span class="glyphicon glyphicon-user"></span>  
                                    <!-- <img src="./dingding.png" alt="头像" class="img-circle naver"> -->
                                    <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'users:personal'  %}?id={{ request.user.id }}">个人中心</a></li>
                                    <li><a href="#">修改密码</a></li>
                                    <li><a href="#">修改头像</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="{% url 'users:usersLogout' %}">退出</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
        </header>
        <div class="row">
                <div class="col-md-10 ">
                        <div class="content">
                            {% block content %}
                            {% endblock %}
                        </div>
                    </div>
            </div>
        </div>

</body>




</html>